package com.sushanth.dontscroll.data

import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager

fun getInstalledApps(context: Context): List<InstalledApp> {
    val packageManager = context.packageManager

    @Suppress("DEPRECATION")
    val packages = packageManager.getInstalledApplications(
        PackageManager.GET_META_DATA
    )

    return packages
        .filter { appInfo ->
            appInfo.packageName != context.packageName
        }
        .map { appInfo ->

            val label = packageManager
                .getApplicationLabel(appInfo)
                .toString()

            InstalledApp(
                packageName = appInfo.packageName,
                displayName = label,
                icon = appInfo.loadIcon(packageManager)
            )
        }
        .distinctBy { it.packageName }
        .sortedBy {
            it.displayName.lowercase()
        }
}